CREATE SCHEMA IF NOT EXISTS rental;
use rental;

DROP TABLE IF EXISTS reservation;
DROP TABLE IF EXISTS car;
DROP TABLE IF EXISTS customer;


CREATE TABLE  car (
  CAR_ID int(10)  NOT NULL AUTO_INCREMENT,
  BRAND varchar(10) NOT NULL,
  MODEL varchar(20) NOT NULL,
  ENGINE_TYPE varchar(20) NOT NULL,
  COLOUR varchar(20) NOT NULL,
  YEAR varchar(20) NOT NULL,
  PRIMARY KEY (CAR_ID)
);

CREATE TABLE customer (
  CUSTOMER_ID int(10) NOT NULL AUTO_INCREMENT,
  FIRST_NAME varchar(10) NOT NULL,
  LAST_NAME varchar(20) NOT NULL,
  EMAIL varchar(20) NOT NULL,
  PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE reservation (
  RESERVATION_ID int(10) NOT NULL AUTO_INCREMENT,
  CUSTOMER_ID int(10) NOT NULL,
  CAR_ID int(10) NOT NULL,
  START_DATE date NOT NULL,
  END_DATE date NOT NULL,
  PRIMARY KEY (RESERVATION_ID),
  FOREIGN KEY (CUSTOMER_ID) REFERENCES customer(CUSTOMER_ID),
  FOREIGN KEY (CAR_ID) REFERENCES car(CAR_ID)
);



